In [7]:
import numpy as np

x = np.sin(np.pi/2)

print(x)

1.0


In [6]:
arr = np.array([np.pi/2, np.pi/3, np.pi/4])

print(arr)

[1.57079633 1.04719755 0.78539816]


In [10]:
#converting degree to radian
arr = np.array([90, 180, 270, 360])

x = np.deg2rad(arr)

print(x)

[1.57079633 3.14159265 4.71238898 6.28318531]


In [11]:
#converting radian to degree 
arr = np.array([np.pi/2, np.pi, 1.5*np.pi, 2*np.pi])

x = np.rad2deg(arr)

print(x)

[ 90. 180. 270. 360.]


In [13]:
#finding angles

x = np.arcsin(0.88)
y = np.arccos(0.88)
z = np.arctan(0.88)

# x, y, z = np.arcsin(0.88), np.arccos(0.88), np.arctan(0.88) Also can be written like this. more time efficient 

print(x, y, z)

1.075862200454001 0.4949341263408955 0.7216548508647612


In [15]:
#finding angles from an array

arr = np.array([1, -1, 0.1])

x = np.arcsin(arr)

print(x)

[ 1.57079633 -1.57079633  0.10016742]


In [17]:
#finding hypotenuse using Pythagoras theorem

base = 3
perp = 4

x = np.hypot(base, perp)

print(x)

5.0
