In [6]:
#adding, subtracting, multiplying, and dividing two arrays
import numpy as np

array1 = np.array([14,22,36,44,60,86,57,83,97,10])
array2 = np.array([1,2,3,4,5,6,7,8,9,10])

new_array_add = np.add(array1, array2)
print(new_array_add)

new_array_sub = np.subtract(array1, array2)
print(new_array_sub)

new_array_mult = np.multiply(array1, array2)
print(new_array_mult)

new_array_div = np.divide(array1, array2)
print(new_array_div)

[ 15  24  39  48  65  92  64  91 106  20]
[13 20 33 40 55 80 50 75 88  0]
[ 14  44 108 176 300 516 399 664 873 100]
[14.         11.         12.         11.         12.         14.33333333
  8.14285714 10.375      10.77777778  1.        ]


In [17]:
#remainders, mod and absolute values

import numpy as np

arr1 = np.array([14,32,56,103,243,48,35,98])
arr2 = np.array([1,2,5,6,83,7,4,65])
arr3 = np.array([1,0,-2,5,-6,83,-7,4,-55])

new_arr_rmndr = np.mod(arr1, arr2) #np.remainder() does the same as well
print(new_arr_rmndr)

new_arr_divmod = np.divmod(arr1, arr2) #first one shows the quotients and the last one is the remainder
print(new_arr_divmod)

new_arr_abs = np.absolute(arr3)
print(new_arr_abs)

[ 0  0  1  1 77  6  3 33]
(array([14, 16, 11, 17,  2,  6,  8,  1]), array([ 0,  0,  1,  1, 77,  6,  3, 33]))
[ 1  0  2  5  6 83  7  4 55]


In [45]:
#ROUNDING VALUES

import numpy as np

arr = np.array([-5.23, 9.63])

truncation_array = np.trunc(arr)
print(truncation_array)

fix_array = np.fix(arr)
print(fix_array)          # trunc() and fix() does the same thing

arr1 = np.around(3.3256, 2) #rounds the value around(value, decimal number)
print(arr1)

floor_array = np.floor(arr)
print(floor_array)

ceil_array = np.ceil(arr)
print(ceil_array)

# ^ also can be written as,

arr = np.ceil([-5.23, 9.63])
print(arr)

[-5.  9.]
[-5.  9.]
3.33
[-6.  9.]
[-5. 10.]
[-5. 10.]


In [46]:
#LOGARITHM

import numpy as np

array = np.arange(1, 10)

print(np.log(array)) #for natural log
print(np.log2(array)) #for calculating log with base 2
print(np.log10(array)) #for calculating log with base 10

[0.         0.69314718 1.09861229 1.38629436 1.60943791 1.79175947
 1.94591015 2.07944154 2.19722458]
[0.         1.         1.5849625  2.         2.32192809 2.5849625
 2.80735492 3.         3.169925  ]
[0.         0.30103    0.47712125 0.60205999 0.69897    0.77815125
 0.84509804 0.90308999 0.95424251]
